#!/command/with-contenv bash
# shellcheck shell=bash

cd /app/

exec s6-setuidgid machine-learner \
    /usr/local/bin/granian \
        --host 0.0.0.0 \
        --port 8000 \
        --interface asgi \
        --no-ws \
        main:app
