# Generated by Django 4.1.9 on 2023-08-04 07:38

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1036_alter_savedviewfilterrule_rule_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="correspondent",
            name="backend_id",
            field=models.IntegerField(
                default=0,
                help_text="Backend ID of this correspondent",
                unique=True,
                verbose_name="Backend id of this correspondent",
            ),
        ),
        migrations.AddField(
            model_name="correspondent",
            name="member_id",
            field=models.IntegerField(
                blank=True,
                default=None,
                help_text="Member ID of this correspondent. Only used if this is a member",
                null=True,
                unique=True,
                verbose_name="Member number of this correspondent",
            ),
        ),
    ]
